pool:
  vmImage: 'windows-latest'

# Trigger production build (i.e. Nuget publish) after successful build pipeline run on main branch
resources:
  pipelines:
    - pipeline: WkHtmlConverterBuild
      source: "WkHtmlConverterBuild"
      trigger:
        enabled: true
        branches:
          include:
            - main

trigger: none
pr: none

variables:
  - group: SharedVariables

steps:
- download: WkHtmlConverterBuild
  artifact: NuGetPackage

- task: UseDotNet@2 # ensure the .NET Core SDK is installed

- script: dotnet -d nuget push $(Pipeline.Workspace)\WkHtmlConverter.*.nupkg --api-key $(NuGetApiKey) --source https://api.nuget.org/v3/index.json

