pool:
  vmImage: 'windows-latest'

# Trigger production build (i.e. Nuget publish) after successful build pipeline run on main branch
resources:
  pipelines:
    - pipeline: WkHtmlConverterBuild
      source: "WkHtmlConverterBuild"
      trigger:
        enabled: true
        branches:
          include:
            - main

trigger: none
pr: none

variables:
  - group: SharedVariables

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: NuGetPackage
    path: $(Build.SourcesDirectory)

- task: UseDotNet@2 # ensure the .NET Core SDK is installed

- script: dotnet nuget push $(Build.SourcesDirectory)\WkHtmlConverter.*.nupkg --api-key $(NuGetApiKey)

